export const categories = [
  "Antiques & Collectables",
  "Art",
  "Astrology & Metaphysical",
  "Automotive",
  "Baby",
  "Books & Magazines",
  "Cameras & Equipment",
  "Cell Phones & Accessories",
  "Clothing & Accessories",
  "Coins, Stamps & Paper Money",
  "Collectables",
  "Computers/Tablets & Networking",
  "Consumer Electronics",
  "Crafts",
  "Dolls & Bears",
  "DVDs & Movies",
  "Entertainment & Memorabilia",
  "Gift Cards & Coupons",
  "Health & Beauty",
  "Home Goods & Decor",
  "Jewelry & Watches",
  "Miscellaneous",
  "Music",
  "Musical Instruments & Gear",
  "Pet Supplies",
  "Pottery & Glass",
  "Sporting Goods",
  "Sports Memorabilia & Trading Cards",
  "Tickets & Experiences",
  "Toys & Games",
];